// SPDX-License-Identifier: GPL-3.0-only
/*
 * Copyright (C) 2026  robinpie <robin413@protonmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* config.c - locate, parse and apply the user config file.
 *
 * The config lives at $XDG_CONFIG_HOME/viewpoint/viewpoint.conf, falling back
 * to ~/.config/viewpoint/viewpoint.conf when XDG_CONFIG_HOME is unset. It is an
 * optional, line-oriented "key = value" file:
 *
 *     # comments run to end of line
 *     bind   = alt+enter   new          # add or change a chord
 *     unbind = alt+f4                    # drop a default chord
 *     toggle = f12                       # the INTERPRET/PASSTHROUGH key
 *     scrollback  = 2000                 # per-window history lines
 *     scroll_step = 3                    # lines per mouse-wheel notch
 *
 * The keymap starts as a copy of the built-in defaults (input.c), which the
 * bind/unbind lines then edit. Recognized keys are dispatched in config_apply();
 * add cases there as more tunables appear. Chord and action name parsing lives
 * in input.c, next to the keymap it builds.
 */
#define _GNU_SOURCE
#include "viewpoint.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/stat.h>
#include <errno.h>

bool config_path(char *buf, size_t buflen)
{
	int n;
	const char *xdg = getenv("XDG_CONFIG_HOME");
	if (xdg && *xdg) {
		n = snprintf(buf, buflen, "%s/viewpoint/viewpoint.conf", xdg);
	} else {
		const char *home = getenv("HOME");
		if (!home || !*home) {
			return false;
		}
		n = snprintf(buf, buflen, "%s/.config/viewpoint/viewpoint.conf",
			     home);
	}
	return n > 0 && (size_t)n < buflen;
}

static char *trim(char *s)
{
	while (*s && isspace((unsigned char)*s)) {
		s++;
	}
	char *end = s + strlen(s);
	while (end > s && isspace((unsigned char)end[-1])) {
		*--end = '\0';
	}
	return s;
}

/* Section markers in the on-disk file. Everything above the in-app marker is
 * the user's "manual" section (preserved verbatim on save); everything below it
 * is regenerated by config_save() from in-app/automatic changes. */
#define CFG_TOP_HDR "# viewpoint config"
#define CFG_MANUAL_HDR "# manual configuration:"
#define CFG_INAPP_HDR "# in-app/automatically set configuration:"

/* Markers are matched by prefix (after trimming) so trailing content on the
 * marker line - e.g. "# manual configuration: (your settings)" - still flags
 * the section instead of being silently swallowed into the wrong block. */
static bool is_marker(const char *line, const char *marker)
{
	return strncmp(line, marker, strlen(marker)) == 0;
}

static bool parse_hex_color(const char *s, vp_rgb *out)
{
	if (*s == '#') {
		s++;
	}
	char *end = NULL;
	unsigned long v = strtoul(s, &end, 16);
	if (end == s || *trim(end) != '\0' || v > 0xffffffUL) {
		return false;
	}
	*out = (vp_rgb)v;
	return true;
}

static bool set_color_override(VpConfig *cfg, int idx, vp_rgb color)
{
	for (int i = 0; i < cfg->n_color_overrides; i++) {
		if (cfg->color_overrides[i].field_idx == idx) {
			cfg->color_overrides[i].color = color;
			return true;
		}
	}
	if (cfg->n_color_overrides == cfg->color_cap) {
		int nc = cfg->color_cap ? cfg->color_cap * 2 : 8;
		VpColorOverride *n = realloc(cfg->color_overrides,
					    (size_t)nc * sizeof(*n));
		if (!n) {
			return false;
		}
		cfg->color_overrides = n;
		cfg->color_cap = nc;
	}
	cfg->color_overrides[cfg->n_color_overrides].field_idx = idx;
	cfg->color_overrides[cfg->n_color_overrides].color = color;
	cfg->n_color_overrides++;
	return true;
}

bool config_set_color_override(VpConfig *cfg, int idx, vp_rgb color)
{
	return set_color_override(cfg, idx, color);
}

void config_clear_color_override(VpConfig *cfg, int idx)
{
	for (int i = 0; i < cfg->n_color_overrides; i++) {
		if (cfg->color_overrides[i].field_idx == idx) {
			cfg->color_overrides[i] =
				cfg->color_overrides[--cfg->n_color_overrides];
			return;
		}
	}
}

bool config_has_color_override(const VpConfig *cfg, int idx, vp_rgb *out)
{
	for (int i = 0; i < cfg->n_color_overrides; i++) {
		if (cfg->color_overrides[i].field_idx == idx) {
			if (out) {
				*out = cfg->color_overrides[i].color;
			}
			return true;
		}
	}
	return false;
}

/* Apply one parsed key/value pair to cfg. Returns false for unknown keys or
 * malformed values. line is supplied only for diagnostics. */
static bool config_apply(VpConfig *cfg, const char *key, char *val, int line)
{
	if (strcmp(key, "bind") == 0) {
		/* value is "<chord> <action>" */
		char *sp = val;
		while (*sp && !isspace((unsigned char)*sp)) {
			sp++;
		}
		if (*sp == '\0') {
			vp_log("config: line %d: bind needs '<chord> <action>'\n",
			       line);
			return false;
		}
		*sp = '\0';
		char *action = trim(sp + 1);
		return keymap_bind(cfg, val, action);
	}
	if (strcmp(key, "unbind") == 0) {
		return keymap_unbind(cfg, val);
	}
	if (strcmp(key, "toggle") == 0) {
		return keymap_set_toggle(cfg, val);
	}
	if (strcmp(key, "scrollback") == 0) {
		char *end = NULL;
		long n = strtol(val, &end, 10);
		if (end == val || *trim(end) != '\0' || n < 0 ||
		    n > VP_SCROLLBACK_LIMIT) {
			vp_log("config: line %d: scrollback needs 0..%d\n",
			       line, VP_SCROLLBACK_LIMIT);
			return false;
		}
		cfg->scrollback_max = (int)n;
		return true;
	}
	if (strcmp(key, "scroll_step") == 0) {
		char *end = NULL;
		long n = strtol(val, &end, 10);
		if (end == val || *trim(end) != '\0' || n < 1 ||
		    n > VP_SCROLL_STEP_MAX) {
			vp_log("config: line %d: scroll_step needs 1..%d\n",
			       line, VP_SCROLL_STEP_MAX);
			return false;
		}
		cfg->scroll_step = (int)n;
		return true;
	}
	if (strcmp(key, "icon") == 0) {
		/* value is "<name> <x> <y>" - a desktop launcher icon's top-left cell */
		char name[16];
		int x, y;
		if (sscanf(val, "%15s %d %d", name, &x, &y) != 3) {
			vp_log("config: line %d: icon needs '<name> <x> <y>'\n",
			       line);
			return false;
		}
		if (strcmp(name, "settings") == 0) {
			cfg->settings_icon_x = x;
			cfg->settings_icon_y = y;
		} else if (strcmp(name, "exit") == 0) {
			cfg->exit_icon_x = x;
			cfg->exit_icon_y = y;
		} else {
			vp_log("config: line %d: unknown icon '%s'\n", line,
			       name);
			return false;
		}
		return true;
	}
	if (strcmp(key, "theme") == 0) {
		if (!vp_theme_builtin(val)) {
			vp_log("config: line %d: unknown theme '%s'\n", line,
			       val);
			return false;
		}
		free(cfg->theme_name);
		cfg->theme_name = strdup(val);
		return true;
	}
	if (strcmp(key, "background") == 0) {
		/* "solid" | "pattern <glyph>" | "image <path>" */
		char *sp = val;
		while (*sp && !isspace((unsigned char)*sp)) {
			sp++;
		}
		char *arg = NULL;
		if (*sp) {
			*sp = '\0';
			arg = trim(sp + 1);
		}
		if (strcmp(val, "solid") == 0) {
			cfg->bg_mode = BG_SOLID;
		} else if (strcmp(val, "pattern") == 0) {
			cfg->bg_mode = BG_PATTERN;
			if (arg && *arg) {
				free(cfg->bg_glyph);
				cfg->bg_glyph = strdup(arg);
			}
		} else if (strcmp(val, "image") == 0) {
			if (!arg || !*arg) {
				vp_log("config: line %d: background image needs a path\n",
				       line);
				return false;
			}
			cfg->bg_mode = BG_IMAGE;
			free(cfg->bg_image_path);
			cfg->bg_image_path = strdup(arg);
		} else {
			vp_log("config: line %d: background needs solid|pattern|image\n",
			       line);
			return false;
		}
		return true;
	}
	if (strcmp(key, "bg_fit") == 0) {
		if (strcmp(val, "stretch") == 0) {
			cfg->bg_fit = FIT_STRETCH;
		} else if (strcmp(val, "scale") == 0) {
			cfg->bg_fit = FIT_SCALE;
		} else if (strcmp(val, "center") == 0) {
			cfg->bg_fit = FIT_CENTER;
		} else if (strcmp(val, "tile") == 0) {
			cfg->bg_fit = FIT_TILE;
		} else {
			vp_log("config: line %d: bg_fit needs stretch|scale|center|tile\n",
			       line);
			return false;
		}
		return true;
	}
	if (strcmp(key, "keep_customizations") == 0) {
		if (strcmp(val, "true") == 0 || strcmp(val, "1") == 0 ||
		    strcmp(val, "yes") == 0) {
			cfg->keep_customizations = true;
		} else if (strcmp(val, "false") == 0 || strcmp(val, "0") == 0 ||
			   strcmp(val, "no") == 0) {
			cfg->keep_customizations = false;
		} else {
			vp_log("config: line %d: keep_customizations needs true/false\n",
			       line);
			return false;
		}
		return true;
	}
	if (strcmp(key, "color") == 0) {
		/* "<element> <hex>" */
		char name[32];
		char hex[16];
		if (sscanf(val, "%31s %15s", name, hex) != 2) {
			vp_log("config: line %d: color needs '<element> <hex>'\n",
			       line);
			return false;
		}
		int idx = vp_theme_field_index(name);
		if (idx < 0) {
			vp_log("config: line %d: unknown color element '%s'\n",
			       line, name);
			return false;
		}
		vp_rgb c;
		if (!parse_hex_color(hex, &c)) {
			vp_log("config: line %d: bad color hex '%s'\n", line,
			       hex);
			return false;
		}
		return set_color_override(cfg, idx, c);
	}
	vp_log("config: line %d: unknown key '%s'\n", line, key);
	return false;
}

static void config_apply_line(VpConfig *cfg, char *buf, int line)
{
	char *s = trim(buf);
	if (*s == '\0' || *s == '#') {
		return;
	}
	char *eq = strchr(s, '=');
	if (!eq) {
		vp_log("config: line %d: expected 'key = value', got '%s'\n",
		       line, s);
		return;
	}
	*eq = '\0';
	char *key = trim(s);
	char *val = trim(eq + 1);
	config_apply(cfg, key, val, line);
}

static char *buf_append(char *b, size_t *len, size_t *cap, const char *s)
{
	size_t add = strlen(s);
	if (*len + add + 1 > *cap) {
		size_t nc = *cap ? *cap * 2 : 256;
		while (nc < *len + add + 1) {
			nc *= 2;
		}
		char *n = realloc(b, nc);
		if (!n) {
			return b; /* drop the line rather than crash; best-effort capture */
		}
		b = n;
		*cap = nc;
	}
	memcpy(b + *len, s, add);
	*len += add;
	b[*len] = '\0';
	return b;
}

static void config_apply_text(VpConfig *cfg, const char *text)
{
	if (!text) {
		return;
	}
	int line = 0;
	char lb[1024];
	for (const char *p = text; *p;) {
		const char *nl = strchr(p, '\n');
		size_t len = nl ? (size_t)(nl - p) : strlen(p);
		if (len >= sizeof(lb)) {
			len = sizeof(lb) - 1;
		}
		memcpy(lb, p, len);
		lb[len] = '\0';
		config_apply_line(cfg, lb, ++line);
		if (!nl) {
			break;
		}
		p = nl + 1;
	}
}

void config_defaults(VpConfig *cfg)
{
	memset(cfg, 0, sizeof(*cfg));
	keymap_load_defaults(cfg);
	/* -1 = "unset": use each icon's built-in default placement. */
	cfg->settings_icon_y = cfg->settings_icon_x = -1;
	cfg->exit_icon_y = cfg->exit_icon_x = -1;
	cfg->scrollback_max = VP_SCROLLBACK_MAX;
	cfg->scroll_step = VP_SCROLL_STEP;
	cfg->theme_name = NULL;
	cfg->bg_mode = -1;
	cfg->bg_fit = FIT_STRETCH;
	cfg->bg_glyph = NULL;
	cfg->bg_image_path = NULL;
	cfg->keep_customizations = false;
	cfg->color_overrides = NULL;
	cfg->n_color_overrides = cfg->color_cap = 0;
}

void config_free(VpConfig *cfg)
{
	free(cfg->keymap);
	cfg->keymap = NULL;
	cfg->nkeys = 0;
	cfg->keycap = 0;
	free(cfg->manual_text);
	cfg->manual_text = NULL;
	free(cfg->theme_name);
	cfg->theme_name = NULL;
	free(cfg->bg_glyph);
	cfg->bg_glyph = NULL;
	free(cfg->bg_image_path);
	cfg->bg_image_path = NULL;
	free(cfg->color_overrides);
	cfg->color_overrides = NULL;
	cfg->n_color_overrides = cfg->color_cap = 0;
}

/* Create each directory along `path` (which names a file). Like `mkdir -p` on
 * the dirname. Best-effort: existing dirs are fine, other errors are ignored
 * here and surface as the fopen failure in config_save. */
static void mkdir_parents(const char *path)
{
	char tmp[1024];
	if (snprintf(tmp, sizeof(tmp), "%s", path) >= (int)sizeof(tmp)) {
		return;
	}
	for (char *p = tmp + 1; *p; p++) {
		if (*p == '/') {
			*p = '\0';
			if (mkdir(tmp, 0755) != 0 && errno != EEXIST) {
				/* keep going; the final fopen reports the real problem */
			}
			*p = '/';
		}
	}
}

static int chord_action(const VpConfig *cfg, uint32_t id, unsigned mods)
{
	for (int i = 0; i < cfg->nkeys; i++) {
		if (cfg->keymap[i].id == id && cfg->keymap[i].mods == mods) {
			return (int)cfg->keymap[i].act;
		}
	}
	return -1;
}

static bool setting_differs(const VpConfig *a, const VpConfig *b, vp_setting s);

/* Write the lines that turn `base` (= defaults + manual section) into the live
 * keymap `cfg`. This is a minimal chord-level diff so the in-app section stays
 * small and only conflicting manual settings are overridden (by later-wins). */
static void write_inapp_diff(FILE *f, const VpConfig *cfg, const VpConfig *base)
{
	char chord[64];

	if (cfg->toggle_key != base->toggle_key) {
		keymap_format_chord(cfg->toggle_key, 0, chord, sizeof(chord));
		fprintf(f, "toggle = %s\n", chord);
	}

	/* Terminal tunables, only when they differ from the baseline. */
	if (cfg->scrollback_max != base->scrollback_max) {
		fprintf(f, "scrollback = %d\n", cfg->scrollback_max);
	}
	if (cfg->scroll_step != base->scroll_step) {
		fprintf(f, "scroll_step = %d\n", cfg->scroll_step);
	}

	/* Desktop icon positions, only when set and differing from the baseline (so
     * a position already pinned by the manual section isn't echoed here). */
	if (cfg->settings_icon_y >= 0 &&
	    (cfg->settings_icon_y != base->settings_icon_y ||
	     cfg->settings_icon_x != base->settings_icon_x)) {
		fprintf(f, "icon = settings %d %d\n", cfg->settings_icon_x,
			cfg->settings_icon_y);
	}
	if (cfg->exit_icon_y >= 0 && (cfg->exit_icon_y != base->exit_icon_y ||
				      cfg->exit_icon_x != base->exit_icon_x)) {
		fprintf(f, "icon = exit %d %d\n", cfg->exit_icon_x,
			cfg->exit_icon_y);
	}

	if (cfg->keep_customizations != base->keep_customizations) {
		fprintf(f, "keep_customizations = %s\n",
			cfg->keep_customizations ? "true" : "false");
	}

	if (cfg->theme_name &&
	    (!base->theme_name ||
	     strcmp(cfg->theme_name, base->theme_name) != 0)) {
		fprintf(f, "theme = %s\n", cfg->theme_name);
	}

	if (cfg->bg_mode >= 0 && setting_differs(cfg, base, SETTING_BACKGROUND)) {
		if (cfg->bg_mode == BG_SOLID) {
			fprintf(f, "background = solid\n");
		} else if (cfg->bg_mode == BG_PATTERN) {
			fprintf(f, "background = pattern %s\n",
				cfg->bg_glyph ? cfg->bg_glyph : "·");
		} else if (cfg->bg_mode == BG_IMAGE) {
			fprintf(f, "background = image %s\n",
				cfg->bg_image_path ? cfg->bg_image_path : "");
		}
		if (cfg->bg_mode == BG_IMAGE) {
			static const char *fits[] = { "stretch", "scale",
						      "center", "tile" };
			if (cfg->bg_fit >= 0 && cfg->bg_fit <= FIT_TILE) {
				fprintf(f, "bg_fit = %s\n", fits[cfg->bg_fit]);
			}
		}
	}

	for (int i = 0; i < cfg->n_color_overrides; i++) {
		int idx = cfg->color_overrides[i].field_idx;
		vp_rgb c = cfg->color_overrides[i].color;
		bool in_base = false;
		for (int j = 0; j < base->n_color_overrides; j++) {
			if (base->color_overrides[j].field_idx == idx &&
			    base->color_overrides[j].color == c) {
				in_base = true;
				break;
			}
		}
		if (!in_base) {
			fprintf(f, "color = %s %06x\n", vp_theme_field_name(idx),
				c);
		}
	}

	for (int i = 0; i < base->nkeys; i++) {
		if (chord_action(cfg, base->keymap[i].id,
				 base->keymap[i].mods) < 0) {
			keymap_format_chord(base->keymap[i].id,
					    base->keymap[i].mods, chord,
					    sizeof(chord));
			fprintf(f, "unbind = %s\n", chord);
		}
	}

	for (int i = 0; i < cfg->nkeys; i++) {
		int ba = chord_action(base, cfg->keymap[i].id,
				      cfg->keymap[i].mods);
		if (ba != (int)cfg->keymap[i].act) {
			keymap_format_chord(cfg->keymap[i].id,
					    cfg->keymap[i].mods, chord,
					    sizeof(chord));
			fprintf(f, "bind = %s %s\n", chord,
				keymap_action_name(cfg->keymap[i].act));
		}
	}
}

static bool manual_touches_action(const VpConfig *defs, const VpConfig *mbase,
				  vp_action act)
{
	for (int i = 0; i < defs->nkeys; i++) {
		if (defs->keymap[i].act == act &&
		    chord_action(mbase, defs->keymap[i].id,
				 defs->keymap[i].mods) != (int)act) {
			return true;
		}
	}
	for (int i = 0; i < mbase->nkeys; i++) {
		if (mbase->keymap[i].act == act &&
		    chord_action(defs, mbase->keymap[i].id,
				 mbase->keymap[i].mods) != (int)act) {
			return true;
		}
	}
	return false;
}

/* Build the baseline pair every shadow check needs: `defs` = built-in defaults,
 * `mbase` = defaults overlaid with the user's manual section only. Returns false
 * (leaving both untouched) when there is no manual section to shadow anything. */
static bool shadow_baseline(const VpConfig *live, VpConfig *defs,
			    VpConfig *mbase)
{
	if (!live->manual_text || !*live->manual_text) {
		return false;
	}
	config_defaults(defs);
	config_defaults(mbase);
	config_apply_text(mbase, live->manual_text);
	return true;
}

/* The single place mapping a scalar setting to the VpConfig field holding it.
 * Add a case here (and a vp_setting value) to extend the shadow check to a new
 * in-app setting. */
static bool setting_differs(const VpConfig *a, const VpConfig *b, vp_setting s)
{
	switch (s) {
	case SETTING_TOGGLE_KEY:
		return a->toggle_key != b->toggle_key;
	case SETTING_SCROLLBACK:
		return a->scrollback_max != b->scrollback_max;
	case SETTING_SCROLL_STEP:
		return a->scroll_step != b->scroll_step;
	case SETTING_THEME:
		return (a->theme_name == NULL) != (b->theme_name == NULL) ||
		       (a->theme_name && b->theme_name &&
			strcmp(a->theme_name, b->theme_name) != 0);
	case SETTING_BACKGROUND: {
		if (a->bg_mode != b->bg_mode || a->bg_fit != b->bg_fit) {
			return true;
		}
		bool ag = a->bg_glyph != NULL, bg = b->bg_glyph != NULL;
		if (ag != bg ||
		    (ag && bg && strcmp(a->bg_glyph, b->bg_glyph) != 0)) {
			return true;
		}
		bool ai = a->bg_image_path != NULL, bi = b->bg_image_path != NULL;
		if (ai != bi ||
		    (ai && bi &&
		     strcmp(a->bg_image_path, b->bg_image_path) != 0)) {
			return true;
		}
		return false;
	}
	case SETTING_KEEP_CUSTOM:
		return a->keep_customizations != b->keep_customizations;
	case SETTING_COLORS: {
		if (a->n_color_overrides != b->n_color_overrides) {
			return true;
		}
		/* Order-independent: every override in `a` must match one in `b`. */
		for (int i = 0; i < a->n_color_overrides; i++) {
			bool found = false;
			for (int j = 0; j < b->n_color_overrides; j++) {
				if (a->color_overrides[i].field_idx ==
					    b->color_overrides[j].field_idx &&
				    a->color_overrides[i].color ==
					    b->color_overrides[j].color) {
					found = true;
					break;
				}
			}
			if (!found) {
				return true;
			}
		}
		return false;
	}
	}
	return false;
}

/* Does this manual-section line assign `key`? If `elem` is non-NULL, also require
 * the value's first token to equal it (for "color = <element> <hex>" lines). The
 * line is matched read-only; a scratch copy is trimmed/split. */
static bool line_sets_key(const char *line, const char *key, const char *elem)
{
	char buf[1024];
	snprintf(buf, sizeof(buf), "%.*s", (int)sizeof(buf) - 1, line);
	char *s = trim(buf);
	if (*s == '#' || *s == '\0') {
		return false;
	}
	char *eq = strchr(s, '=');
	if (!eq) {
		return false;
	}
	*eq = '\0';
	if (strcmp(trim(s), key) != 0) {
		return false;
	}
	if (elem) {
		char *val = trim(eq + 1);
		char *sp = val;
		while (*sp && !isspace((unsigned char)*sp)) {
			sp++;
		}
		*sp = '\0';
		if (strcmp(val, elem) != 0) {
			return false;
		}
	}
	return true;
}

/* Remove every manual-section line that assigns `key` (optionally narrowed to a
 * single color `elem`), so an in-app change to that setting is no longer shadowed
 * on the next load. Returns true if anything was removed. */
static bool manual_drop_key(VpConfig *cfg, const char *key, const char *elem)
{
	if (!cfg->manual_text) {
		return false;
	}
	char *out = NULL;
	size_t len = 0, cap = 0;
	bool changed = false;
	for (const char *p = cfg->manual_text; *p;) {
		const char *nl = strchr(p, '\n');
		size_t llen = nl ? (size_t)(nl - p) : strlen(p);
		char line[1024];
		size_t cpy = llen < sizeof(line) ? llen : sizeof(line) - 1;
		memcpy(line, p, cpy);
		line[cpy] = '\0';
		if (line_sets_key(line, key, elem)) {
			changed = true; /* drop it */
		} else {
			out = buf_append(out, &len, &cap, line);
			out = buf_append(out, &len, &cap, "\n");
		}
		if (!nl) {
			break;
		}
		p = nl + 1;
	}
	if (changed) {
		free(cfg->manual_text);
		cfg->manual_text = out; /* NULL if every line was dropped */
	} else {
		free(out);
	}
	return changed;
}

void config_manual_override(VpConfig *cfg, vp_setting setting)
{
	switch (setting) {
	case SETTING_THEME:
		manual_drop_key(cfg, "theme", NULL);
		break;
	case SETTING_BACKGROUND:
		manual_drop_key(cfg, "background", NULL);
		manual_drop_key(cfg, "bg_fit", NULL);
		break;
	case SETTING_KEEP_CUSTOM:
		manual_drop_key(cfg, "keep_customizations", NULL);
		break;
	case SETTING_TOGGLE_KEY:
	case SETTING_SCROLLBACK:
	case SETTING_SCROLL_STEP:
	case SETTING_COLORS:
		break; /* not handled here (colors are per-element below) */
	}
}

void config_manual_override_color(VpConfig *cfg, int field_idx)
{
	const char *name = vp_theme_field_name(field_idx);
	if (name) {
		manual_drop_key(cfg, "color", name);
	}
}

bool config_manual_shadows_setting(const VpConfig *live, vp_setting setting)
{
	VpConfig defs, mbase;
	if (!shadow_baseline(live, &defs, &mbase)) {
		return false;
	}
	/* Shadowed when the manual section sets this value away from the default:
     * whatever the in-app change writes, the manual section reasserts on load. */
	bool shadow = setting_differs(&defs, &mbase, setting);
	config_free(&defs);
	config_free(&mbase);
	return shadow;
}

bool config_manual_shadows_action(const VpConfig *live, vp_action act,
				  uint32_t id, unsigned mods)
{
	VpConfig defs, mbase;
	if (!shadow_baseline(live, &defs, &mbase)) {
		return false;
	}
	/* Shadowed if the manual section governs this action, or the chord we're
     * assigning (it would reassert its own meaning on reload). */
	bool shadow = manual_touches_action(&defs, &mbase, act) ||
		      (chord_action(&defs, id, mods) !=
		       chord_action(&mbase, id, mods));
	config_free(&defs);
	config_free(&mbase);
	return shadow;
}

bool config_save(const VpConfig *cfg)
{
	char path[1024];
	if (!config_path(path, sizeof(path))) {
		vp_log("config: cannot resolve path for save\n");
		return false;
	}
	mkdir_parents(path);

	FILE *f = fopen(path, "w");
	if (!f) {
		vp_log("config: cannot write %s (%s)\n", path, strerror(errno));
		return false;
	}

	/* Baseline the in-app section is diffed against: built-in defaults overlaid
     * with the user's manual section only. */
	VpConfig base;
	config_defaults(&base);
	config_apply_text(&base, cfg->manual_text);

	/* Autogenerated section first; manual section last so it wins (later lines
     * override earlier ones at load time). */
	fprintf(f, "%s\n\n", CFG_TOP_HDR);
	fprintf(f, "%s\n", CFG_INAPP_HDR);
	fprintf(f,
		"# Do not edit this section manually. It is rewritten automatically whenever settings change in-app. Later lines win, so anything in the manual section below overrides bindings set here.\n");
	write_inapp_diff(f, cfg, &base);
	fprintf(f, "\n%s\n", CFG_MANUAL_HDR);
	if (cfg->manual_text && *cfg->manual_text) {
		fputs(cfg->manual_text, f);
		size_t n = strlen(cfg->manual_text);
		if (cfg->manual_text[n - 1] != '\n') {
			fputc('\n', f);
		}
	}

	config_free(&base);
	bool ok = (fflush(f) == 0);
	fclose(f);
	vp_log("config: saved %s\n", path);
	return ok;
}

void config_load(VpConfig *cfg)
{
	config_defaults(cfg);

	char path[1024];
	if (!config_path(path, sizeof(path))) {
		vp_log("config: could not resolve config path (no HOME/XDG_CONFIG_HOME)\n");
		return;
	}
	vp_log("config: path = %s\n", path);

	FILE *f = fopen(path, "r");
	if (!f) {
		/* Absent config is the normal case - run with built-in defaults. */
		vp_log("config: no file at %s; using defaults\n", path);
		return;
	}

	/* Apply every line to the live keymap in file order (in-app section then
     * manual section, so the manual section wins). Separately capture the manual
     * section verbatim so config_save() can preserve it.
     *
     * Sections: 0 = preamble (before any marker), 1 = in-app, 2 = manual. A
     * file with no markers at all (hand-written) is treated as entirely manual. */
	char *pre = NULL;
	size_t prelen = 0, precap = 0;
	char *man = NULL;
	size_t manlen = 0, mancap = 0;
	int sec = 0;
	bool saw_marker = false;

	char buf[1024];
	int line = 0;
	while (fgets(buf, sizeof(buf), f)) {
		line++;

		char tmp[1024];
		snprintf(tmp, sizeof(tmp), "%s", buf);
		const char *t = trim(tmp);

		if (is_marker(t, CFG_INAPP_HDR)) {
			sec = 1;
			saw_marker = true;
			continue; /* markers aren't captured/applied */
		}
		if (is_marker(t, CFG_MANUAL_HDR)) {
			sec = 2;
			saw_marker = true;
			continue;
		}

		if (sec == 0) {
			if (!is_marker(t, CFG_TOP_HDR)) {
				pre = buf_append(pre, &prelen, &precap, buf);
			}
		} else if (sec == 2) {
			man = buf_append(man, &manlen, &mancap, buf);
		}
		/* sec == 1 (in-app) lines are applied but not captured. */

		config_apply_line(cfg, buf, line);
	}

	fclose(f);

	/* A markerless file is all manual; otherwise the manual block is what
     * followed the manual marker. */
	char *manual = saw_marker ? man : pre;
	free(saw_marker ? pre : man);

	if (manual) {
		const char *p = manual;
		while (*p == '\n' || *p == ' ' || *p == '\t' || *p == '\r') {
			p++;
		}
		if (*p == '\0') {
			free(manual);
			manual = NULL;
		}
	}
	cfg->manual_text = manual;
	cfg->loaded = true;
}
